name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  sites:
    description: 'Sites to check split by ","'
    required: true
  gist_id:
    description: 'The id of gist to update'
    required: true
  github_pat:
    description: 'GitHub personal acces token to update gist'
    required: true
outputs:
  cert_data: # output will be available to future steps
    description: 'Certs'
runs:
  using: 'node12'
  main: 'dist/index.js'

