on:
  schedule:
    - cron: "30 2 * * *"
  push:
    branches:
      - master
jobs:
  check:
    name: Check Cert
    runs-on: ubuntu-latest
    steps:
      - name: Check Certificates
        uses: fengkx/cert-check@1.0.0
        with:
          gist_id: '55678154ff2fc462f6de8a872eb75ac1'
          sites: 'https://www.linevil.net , https://www.him.moe'
          github_pat: ${{ secrets.pat }}
