on:
  schedule:
    - cron: "30 2 * * *"
  push:
    branches:
      - master
jobs:
  check:
    name: Check Cert
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout my repository'
        uses: actions/checkout@v2
      - name: 'mkdirp'
        run: 'mkdir -p .github/actions/check-certs'
      - name: 'ls'
        run: 'cp action.yml .github/actions/check-certs/action.yml && ls && ls .github/actions/check-certs'
      - name: 'Run Checker'
        uses: './.github/actions/check-certs'
        with:
          gist_id: '32278de43b1c11c99c62b3e87d9eb5db'
          sites: 'https://www.fengkx.top, https://rss.fengkx.top, https://feedpress.me'
          github_pat: ${{ secrets.GITHUB_PAT }}
